spring:
    h2:
      console:
        path: /h2-console
        enabled: true

    datasource:
      url: jdbc:h2:file:/data/db
      username: admin
      password: admin
      driver-class-name: org.h2.Driver

    jpa:
      show-sql: true
      jpa.database-platform: org.hibernate.dialect.H2Dialect